services:
  redis:
    image: redis:7
    container_name: pigplay-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17
    container_name: pigplay-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pigplay
      POSTGRES_DB: pigplay
      POSTGRES_HOST_AUTH_METHOD: trust  # disables password auth
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
